# Generated by Django 2.0.6 on 2018-06-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='imagem',
            new_name='image',
        ),
    ]
