# Generated by Django 2.0.6 on 2018-07-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180705_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Número (ordem)'),
        ),
    ]
